### ISSUE TITLE
Health Check is failing

### ISSUE THREAD

**Issue by florianeichin** [lux4rd0/kasa-collector#1]
I always get this message. By visiting the code, I cannot find this file at all.

```
kasa-collector    | kasa-init: Starting Health Check
kasa-collector    | /kasa-collector/kasa-collector-init.sh: line 98: ./start-health-check.sh: No such file or directory
```

this is my compose
```yml
services:
  kasa-collector:
    container_name: kasa-collector
    environment:
      TZ: America/Chicago
      KASA_COLLECTOR_COLLECT_INTERVAL: 5
      KASA_COLLECTOR_DEVICE_HOST: 192.168.178.49
      KASA_COLLECTOR_HOST_HOSTNAME: localhost
      KASA_COLLECTOR_INFLUXDB_PASSWORD: none
      KASA_COLLECTOR_INFLUXDB_URL: http://influxdb:8086/write?db=kasa
      KASA_COLLECTOR_INFLUXDB_USERNAME: none
    image: lux4rd0/kasa-collector:latest
    restart: always
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"


version: '3.3'
```
