### ISSUE TITLE
Does collector must be on the same netwokr as smart plugs (IoT vlan) in order for KASA_COLLECTOR_ENABLE_AUTO_DISCOVERY to work?

### ISSUE THREAD

**Issue by TheLinuxGuy** [lux4rd0/kasa-collector#13]
Question about `KASA_COLLECTOR_ENABLE_AUTO_DISCOVERY` and how the application works, could you add more information on how discovery packets work and if it requires to be in the same network as the smart plugs in order for it to work... or if mDNS or other magic allows it to work between different vlans?

My setup is as follows:
- collector is on "server" vlan
- plugs are on "IoT/untrusted" vlan
- server vlan can talk to IoT one way, but the opposite is not true.

**Comment by lux4rd0** [comment]
Great question! Let me explain how Kasa Collector's discovery works and why your VLAN setup is causing issues.

  ## How Kasa Discovery Works

  The collector uses **UDP broadcast packets on port 9999** to discover devices:

  1. Collector sends UDP broadcast to `255.255.255.255:9999`
  2. Kasa devices receive the broadcast and respond back with their information
  3. Collector listens for these UDP responses to build its device list

  This is **not mDNS** - it's TP-Link's proprietary discovery protocol that requires bidirectional UDP communication.

  ## Why Your Setup Doesn't Work

  Your configuration:
  - ✅ Server VLAN → IoT VLAN (collector can send discovery packets)
  - ❌ IoT VLAN → Server VLAN (devices can't send responses back)

  The discovery breaks because while your collector can send the discovery broadcast, the Kasa devices' responses are blocked by your firewall rules.

  ## Solutions for Cross-VLAN Setup

  ### Option 1: Manual Configuration (Recommended)
  Since your server can reach IoT devices, skip discovery entirely:

  ```yaml
  environment:
    KASA_COLLECTOR_ENABLE_AUTO_DISCOVERY: "false"
    KASA_COLLECTOR_DEVICE_HOSTS: "192.168.2.100,192.168.2.101,192.168.2.102"

  This works perfectly with one-way communication because:
  - No UDP discovery needed
  - Collector connects directly via TCP port 9999
  - Only requires Server → IoT communication

  Option 2: Limited Firewall Exception

  Add a minimal rule to allow discovery responses:
  - From: IoT VLAN
  - To: Server VLAN (specifically the collector IP)
  - Port: UDP 9999 (source port)
  - Direction: Return traffic only

  Option 3: Deploy on IoT VLAN

  Run the collector on the same VLAN as your Kasa devices.

  Important Notes

  - UDP broadcasts don't cross VLANs without special configuration
  - Discovery requires bidirectional communication
  - Once devices are known (manual config), only one-way TCP is needed
  - Manual configuration is actually more secure (no broadcast listener)

  For security-conscious setups like yours, I'd recommend Option 1. It eliminates broadcast traffic, reduces attack surface, and works perfectly with
  strict firewall rules.
  ```
